#ifndef SIMULATORCONTROLLERLIBRARY_GLOBAL_H
#define SIMULATORCONTROLLERLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMULATORCONTROLLERLIBRARY_LIBRARY)
#  define SIMULATORCONTROLLERLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIMULATORCONTROLLERLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMULATORCONTROLLERLIBRARY_GLOBAL_H
